# Tarea 2 - Numpy

> lea detalladamente el ejercicio antes de responder los ejercicios

1. Crear los siguientes arregos de numpy
> * Crear un array con 10 elementos 
> * Crear un array con 5 numeros decimales
> * crear un array de 20 elementos con solo  numeros pares

In [1]:

import numpy as np

# Crear un array con 10 elementos
array_10 = np.arange(10)
print(array_10)

# Crear un array con 5 números decimales
array_decimales = np.random.rand(5)
print(array_decimales)

# Crear un array de 20 elementos con solo números pares
array_pares = np.arange(2, 41, 2)
print(array_pares)


[0 1 2 3 4 5 6 7 8 9]
[0.76273291 0.6636829  0.20468846 0.81465007 0.08376104]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


2. Cual es la forma correcta de crear un Array
> * A) np.createArray([1,2,3,4,5])
> * B) np.object([1,2,3,4,5])
> * C) np.array([1,2,3,4,5])

In [2]:

# La forma correcta de crear un array es: C
correcto_array = np.array([1,2,3,4,5])
print(correcto_array)


[1 2 3 4 5]


3. Cual es la forma correcta de saber el numero de dimensiones de un array
> * arr.ndim()
> * arr.dim()   
> * arr.ndim
> * arr.dim

In [3]:
# Forma correcta
zeros_array = np.zeros(4)
print(zeros_array)

[0. 0. 0. 0.]


4. Cual es la sintaxis correcta para imprimir el primer item de un array
> * print(arr,1)
> * print(arr[1])
> * print(arr[0]) 

5. Cual es la sintaxis correcta para imprimir el numero 8 del vector
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
> * print(arr(1,2))
> * print(arr(7,2))
> * print(arr(3,0))

6. Cual es la sintaxis correcta para imprimir [3, 4, 5] del array 
arr = np.array([1,2,3,4,5,6,7])
> * print(arr[3:6])
> * print(arr[2:5])
> * print(arr[2:6])
> * print(arr[2:4])

7. Crear un vector con valores dentro del rango 10 a 49

8. Invertir el vector creado en la pregunta anterior


9. Crear una matriz 3x3 con valores de 0 a 8

10. Crear una matriz identidad de 6x6

11. Encontrar los valores que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

12. Crear una matriz con valores al azar con forma 3x3x3

13. Crear una matriz de 10x10 con 1's en los bordes y cualquier valor en el interior(investigar)

14. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4(investigar)

15. Crear dos arreglos al azar(valores aleatorios) A y B, verificar si son iguales

16. Crear una matrices 10x10 mostrar las siguiente:
> * mostrar las filas 5 en adelante
> * mostrar solo las tres primeras filas
> * mostrar solo las filas 3 a la 7 

17. Crear una matrices 10x10 con valores aleatorios enteros y calcular la suma de valores siguiente:
> * Calcular la suma de todos valores que sean mayores a 25
> * Calcular la suma de los valores por filas que sean mayores a 10 y menores a 25
> * Calcular la suma de los valores por columnas que sean mayores a 50 y menores a 75