# Tarea 2 - Numpy

> lea detalladamente el ejercicio antes de responder los ejercicios

1. Crear los siguientes arregos de numpy
> * Crear un array con 10 elementos 
> * Crear un array con 5 numeros decimales
> * crear un array de 20 elementos con solo  numeros pares

In [2]:
import numpy as np

# Crear un array con 10 elementos
array_de_10 = np.arange(10)
print(array_de_10)

# Crear un array con 5 números decimales
array_de_decimales = np.random.rand(5)
print(array_de_decimales)

# Crear un array de 20 elementos con solo números pares
array_de_pares = np.arange(2, 41, 2)
print( array_de_pares)

[0 1 2 3 4 5 6 7 8 9]
[0.334577   0.41247391 0.46656986 0.07399294 0.25716538]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


2. Cual es la forma correcta de crear un Array
> * A) np.createArray([1,2,3,4,5])
> * B) np.object([1,2,3,4,5])
> * C) np.array([1,2,3,4,5])

In [3]:
# La forma correcta de crear un array es: C
correcto_array = np.array([1,2,3,4,5])
print(correcto_array)

[1 2 3 4 5]


3. Cual es la forma correcta de saber el numero de dimensiones de un array
> * arr.ndim()
> * arr.dim()   
> * arr.ndim
> * arr.dim

In [4]:
import numpy as np

# Array de ejemplo
array_de_ejemplo = np.array([[1, 2, 3], [4, 5, 6]])

# Obtener el número
num_de_dimensiones = array_de_ejemplo.ndim
print( num_de_dimensiones)

2


4. Cual es la sintaxis correcta para imprimir el primer item de un array
> * print(arr,1)
> * print(arr[1])
> * print(arr[0]) 

In [5]:
import numpy as np

# Array de ejemplo
array_ejemplo = np.array([10, 20, 30, 40, 50])

# Imprimir el primer ítem
el_primer_item = array_ejemplo[0]
print(el_primer_item)

10


5. Cual es la sintaxis correcta para imprimir el numero 8 del vector
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
> * print(arr(1,2))
> * print(arr(7,2))
> * print(arr(3,0))

In [6]:
import numpy as np

# Array de ejemplo
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8
print(arr[1, 2])

8


6. Cual es la sintaxis correcta para imprimir [3, 4, 5] del array 
arr = np.array([1,2,3,4,5,6,7])
> * print(arr[3:6])
> * print(arr[2:5])
> * print(arr[2:6])
> * print(arr[2:4])

In [7]:
import numpy as np

# Array de ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir 3, 4, 5
print(arr[2:5])

[3 4 5]


7. Crear un vector con valores dentro del rango 10 a 49

In [8]:
import numpy as np

# Crear el vector
rango_del_vector = np.arange(10, 50)
print(rango_del_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Invertir el vector creado en la pregunta anterior

In [9]:
import numpy as np

# Crear un vector
rango_del_vector = np.arange(10, 50)

# Invertir el vector
vector_invertido = np.flip(rango_del_vector)
print(vector_invertido)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]



9. Crear una matriz 3x3 con valores de 0 a 8

In [10]:
matriz = [[0, 1, 2],[3, 4, 5], [6, 7, 8]]

for fila in matriz: print(fila)


[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


10. Crear una matriz identidad de 6x6

In [11]:
matriz_de_identidad = [[1 if a == b else 0 for a in range(6)] for b in range(6)]

for fila in matriz_de_identidad:print(fila)


[1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 1]


11. Encontrar los valores que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [12]:
arreglo = [1, 2, 4, 2, 4, 0, 1, 0, 0, 0, 12, 4, 5, 6, 7, 0]

valores_no_ceros = [valor for valor in arreglo if valor != 0]

print( valores_no_ceros)


[1, 2, 4, 2, 4, 1, 12, 4, 5, 6, 7]


12. Crear una matriz con valores al azar con forma 3x3x3

In [13]:
import numpy as np

# Crear una matriz random de 3x3x3
matriz_azar = np.random.randint(0, 10, size=(3, 3, 3))

print(matriz_azar)


[[[9 0 4]
  [1 9 2]
  [6 0 5]]

 [[1 4 9]
  [1 9 4]
  [5 7 1]]

 [[7 0 6]
  [3 6 8]
  [4 6 4]]]


13. Crear una matriz de 10x10 con 1's en los bordes y cualquier valor en el interior(investigar)

In [14]:
import numpy as np

# Crear una matriz de 10x10
matrizfin = np.ones((10, 10))

# Actualizar los valores
matrizfin[1:-1, 1:-1] = np.random.randint(1, 10, size=(8, 8))

print(matrizfin)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 7. 3. 6. 3. 8. 8. 2. 6. 1.]
 [1. 8. 3. 8. 8. 3. 9. 2. 5. 1.]
 [1. 3. 2. 1. 2. 1. 9. 3. 3. 1.]
 [1. 5. 4. 6. 9. 8. 7. 6. 2. 1.]
 [1. 8. 2. 5. 6. 5. 6. 2. 2. 1.]
 [1. 3. 1. 1. 3. 6. 4. 1. 3. 1.]
 [1. 9. 9. 3. 4. 1. 8. 3. 4. 1.]
 [1. 6. 5. 5. 4. 2. 3. 8. 8. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


14. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4(investigar)

In [15]:
import numpy as np

# Crear una matriz de 5x5 
matriz = np.tile(np.arange(5), (5, 1))

print(matriz)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


15. Crear dos arreglos al azar(valores aleatorios) A y B, verificar si son iguales

In [16]:
import numpy as np

# Crear dos arreglos
A = np.random.rand(5)
B = np.random.rand(5)

print(A)
print(B)

# Verificar si los arreglos son iguales
son_iguales = np.array_equal(A, B)

# No son iguales 



[0.13918811 0.89602001 0.75736677 0.98277751 0.58595417]
[0.04823867 0.27770331 0.05460816 0.28043544 0.29929022]


16. Crear una matrices 10x10 mostrar las siguiente:
> * mostrar las filas 5 en adelante
> * mostrar solo las tres primeras filas
> * mostrar solo las filas 3 a la 7 

In [17]:
import numpy as np

# Crear una matriz de 10x10
matriz = np.random.randint(1, 100, size=(10, 10))

print(matriz[5:, :])

print(matriz[:3, :])

print(matriz[3:8, :])


[[63 94 62 10 40 26 12 82 83 59]
 [55 25 16 74 93 82 10 74 44 30]
 [85 34  4 44 12 30 62 94 87  2]
 [90 11 83 48 90 54 83 41 14 91]
 [10 11 34 77 32 97 97  4  5 61]]
[[85 75 43 75 42  3  9 57 96 82]
 [48 63 28 21 18 33 61 82 57 23]
 [55 50 65 68 35 39 14 70 63  8]]
[[45 86 76 90 50 44 80 11 55 55]
 [94 55 66 15 50 12 54 42 14 19]
 [63 94 62 10 40 26 12 82 83 59]
 [55 25 16 74 93 82 10 74 44 30]
 [85 34  4 44 12 30 62 94 87  2]]


17. Crear una matrices 10x10 con valores aleatorios enteros y calcular la suma de valores siguiente:
> * Calcular la suma de todos valores que sean mayores a 25
> * Calcular la suma de los valores por filas que sean mayores a 10 y menores a 25
> * Calcular la suma de los valores por columnas que sean mayores a 50 y menores a 75